 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool, IDL.Text],
      [ProductId],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool, IDL.Text],
        [ProductId],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };